"""Compact SQLite-backed PR overlap index."""

from .core import (
    PrOverlapIndex,
    IndexNotInitializedError,
    activate_cold_import_bundle,
    export_cold_import_bundle,
    get_dead_letters,
    get_pr_evidence,
    gc_replay_capsules,
    health_snapshot,
    import_disk_preflight,
    init_db,
    open_existing_index_db,
    record_refresh_failure,
    record_indexer_run,
    refresh_pr,
    replay_capsule,
    restore_import_backup,
    search_pr_overlap,
    upsert_pr_revision,
    validate_cold_import_bundle,
    validate_staging_import_db,
)

__all__ = [
    "PrOverlapIndex",
    "IndexNotInitializedError",
    "activate_cold_import_bundle",
    "export_cold_import_bundle",
    "get_dead_letters",
    "get_pr_evidence",
    "gc_replay_capsules",
    "health_snapshot",
    "import_disk_preflight",
    "init_db",
    "open_existing_index_db",
    "record_refresh_failure",
    "record_indexer_run",
    "refresh_pr",
    "replay_capsule",
    "restore_import_backup",
    "search_pr_overlap",
    "upsert_pr_revision",
    "validate_cold_import_bundle",
    "validate_staging_import_db",
]
